#pragma once

#include <ntddk.h>

#define FILE_DEVICE_EGOTOUCH 0x00008010

#define IOCTL_EGO_PING \
    CTL_CODE(FILE_DEVICE_EGOTOUCH, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_EGO_GET_PROTOCOL_INFO \
    CTL_CODE(FILE_DEVICE_EGOTOUCH, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_EGO_SEND_AFE_COMMAND \
    CTL_CODE(FILE_DEVICE_EGOTOUCH, 0x802, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_EGO_GET_LAST_STATUS \
    CTL_CODE(FILE_DEVICE_EGOTOUCH, 0x803, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_EGO_READ_REGISTER \
    CTL_CODE(FILE_DEVICE_EGOTOUCH, 0x804, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_EGO_WRITE_REGISTER \
    CTL_CODE(FILE_DEVICE_EGOTOUCH, 0x805, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_EGO_GET_FRAME \
    CTL_CODE(FILE_DEVICE_EGOTOUCH, 0x806, METHOD_BUFFERED, FILE_READ_ACCESS)

typedef struct _EGO_PING_REPLY {
    ULONG Version;
    ULONG CapabilityFlags;
    ULONG Reserved;
} EGO_PING_REPLY, *PEGO_PING_REPLY;

typedef struct _EGO_AFE_COMMAND {
    UCHAR Command;
    UCHAR Param;
    UCHAR Reserved[2];
} EGO_AFE_COMMAND, *PEGO_AFE_COMMAND;

typedef struct _EGO_PROTOCOL_INFO {
    ULONG SpiIoctlIntOpen;
    ULONG SpiIoctlIntClose;
    ULONG SpiIoctlWriteRead;
    ULONG SpiIoctlWaitInt;
    ULONG SpiIoctlFullDuplex;
    ULONG SpiIoctlGetFrame;
    ULONG SpiIoctlSetTimeout;
    ULONG SpiIoctlSetBlock;
    ULONG SpiIoctlSetReset;
    ULONG SpiIoctlReadAcpi;
} EGO_PROTOCOL_INFO, *PEGO_PROTOCOL_INFO;

typedef struct _EGO_REGISTER_RW {
    ULONG Address;
    ULONG Length;
    UCHAR Data[256];
} EGO_REGISTER_RW, *PEGO_REGISTER_RW;

typedef struct _EGO_FRAME_REQUEST {
    ULONG Flags;
    ULONG TimeoutMs;
} EGO_FRAME_REQUEST, *PEGO_FRAME_REQUEST;

typedef struct _EGO_FRAME_RESPONSE {
    ULONG DataLength;
    UCHAR Data[6000];
} EGO_FRAME_RESPONSE, *PEGO_FRAME_RESPONSE;
